### ISSUE TITLE
maple-translate displays only the last part of the result in the minibuffer

### ISSUE THREAD

**Issue by lgfang** [honmaple/emacs-maple-translate#3]
In my case, most queries return long results, with the last section containing example sentences. Although the minibuffer expands to multiple lines, it often cannot display the entire result. Consequently, I frequently see only the example sentences, missing the part I am most interested in.

The configuration I am using is:
```
(use-package maple-translate
  :load-path (lambda() (expand-file-name "~/.emacs.d/downloads/emacs-maple-translate"))
  :commands (maple-translate maple-translate+)
  :custom (maple-translate-engine 'youdao)
  :bind (:map global-map
              ("C-h D" . maple-translate)
              ("C-h d" . maple-translate+))
  )
```

**Comment by honmaple** [comment]
You can use custom function instead of `maple-translate`
```
(defun custom-translate(word)
  (interactive (list (maple-translate-word)))
  (let ((maple-translate-section '(basic)))
    (maple-translate-show word 'princ)))
```
